telegram_bot:
  request_timeout: 30s
  poller_timeout: 10s
  ui:
    summary_max_length: 150
    transcript_max_length: 1500
    meetings_per_page: 10
    date_format: 02.01.2006 15:04
salute_speech:
  oauth:
    endpoint: https://ngw.devices.sberbank.ru:9443/api/v2/oauth
    scope: SALUTE_SPEECH_PERS
    refresh_threshold: 2m
    consumer: SaluteSpeech
    supported_formats: PCM_S16LE, OPUS, MP3, FLAC, ALAW, MULAW
  rest_api:
    upload_data: https://smartspeech.sber.ru/rest/v1/data:upload
    async_recognize: https://smartspeech.sber.rurest/v1/speech:async_recognize
    get_task_status: https://smartspeech.sber.rurest/v1/task:get
    download_data: https://smartspeech.sber.ru/rest/v1/data:download
gigachat:
  oauth:
    endpoint: https://ngw.devices.sberbank.ru:9443/api/v2/oauth
    scope: GIGACHAT_API_PERS
    refresh_threshold: 2m
    consumer: GigaChat
  rest_api:
    chat: https://gigachat.devices.sberbank.ru/api/v1/chat/completions
    get_embeddings: https://gigachat.devices.sberbank.ru/api/v1/embeddings
    upload_file: https://gigachat.devices.sberbank.ru/api/v1/files
postgres_db:
  migrations_path: ./migrations
log:
  log_level: info
  is_develop: true
